title: Play Drift Hunters
email: #
description: >-
baseurl: ""
url: "https://play-drift-hunters.github.io"
twitter_username: #
github_username:  #

# Build settings
theme: minima
plugins:
  - jekyll-feed
